name: IOS build and deploy With flutter
on:
  push:
    branches:
      - IOSBuildRelease
jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Import certificates (iOS)
        uses: apple-actions/import-codesign-certs@v1
        with:
          p12-file-base64: ${{ secrets.IOS_P12_DISTRIBUTION_CERT_BASE64 }}
          p12-password: ${{ secrets.IOS_P12_DISTRIBUTION_CERT_PASSWORD }}

      - name: Install the provisioning profile
        env:
          PROVISIONING_CERTIFICATE_BASE64: ${{ secrets.IOS_PROVISION_PROFILE_BASE64 }}
        run: |
          PP_PATH=$RUNNER_TEMP/build_pp.mobileprovision
          echo -n "$PROVISIONING_CERTIFICATE_BASE64" | base64 --decode --output $PP_PATH
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp $PP_PATH ~/Library/MobileDevice/Provisioning\ Profiles
          echo "Listing installed provisioning profiles..."
          ls -la ~/Library/MobileDevice/Provisioning\ Profiles

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.27.2
          channel: stable
          cache: true

      - name: Get dependencies
        run: flutter pub get

      - name: Build iOS application archive
        run: flutter build ios --release --no-codesign

      - name: Build resolve Swift dependencies
        run: xcodebuild -resolvePackageDependencies -workspace ios/Runner.xcworkspace -scheme Runner -configuration Release

      - name: Build xArchive
        run: |
            xcodebuild -workspace ios/Runner.xcworkspace \
            -scheme Runner \
            -configuration Release \
            -sdk iphoneos -destination 'generic/platform=iOS' -archivePath build-output/app.xcarchive \
            DEVELOPMENT_TEAM=YAN363KYTD \
            PROVISIONING_PROFILE=a9fa9ebe-ed8f-4a8e-8549-24cfebb5a6dd \
            clean archive \
            CODE_SIGN_IDENTITY="Apple Distribution: APYA CAPITAL SERVICES PRIVATE LIMITED"

      - name: Export ipa file
        run: xcodebuild -exportArchive -archivePath build-output/app.xcarchive -exportPath build-output/ios -exportOptionsPlist ios/ExportOptions.plist

      - name: Save App Store Connect API Key
        run: |
            mkdir -p ~/.private_keys
            echo -n ${{ secrets.IOS_APPSTORE_CONNECT_API_KEY_BASE64  }} | base64 --decode --output ~/.private_keys/AuthKey_${{ secrets.IOS_APPSTORE_CONNECT_API_KEY_ID }}.p8
            echo "App Store Connect API Key saved!"

      - name: Upload to App Store Connect
        run: |
          echo "Uploading IPA to App Store Connect..."
          xcrun altool --upload-app -f build-output/ios/automate.ipa -t ios --apiKey ${{ secrets.IOS_APPSTORE_CONNECT_API_KEY_ID }} --apiIssuer ${{ secrets.IOS_APPSTORE_CONNECT_ISSUER_ID }}

      - name: Clean up keychain and provisioning profile
        if: ${{ always() }}
        run: |
          rm ~/Library/MobileDevice/Provisioning\ Profiles/build_pp.mobileprovision
